import { publisherHint } from "../lib/publisher";
import type { ClaimStatus, Source, TraceFlag, TraceReport } from "../lib/types";

export const STATUS_LABEL: Record<ClaimStatus, string> = {
  supported: "Has a visible source",
  weak: "Weak / unverified source",
  unsupported: "No visible source",
};

export const FLAG_LABEL: Record<TraceFlag, string> = {
  no_visible_sources: "No sources cited",
  single_source: "Relies on a single source",
  dead_link: "A cited link is dead",
  low_citation_density: "Few claims are sourced",
};

/** A plain-text, paste-anywhere verification note for the current answer. Describes
 * visible sourcing only (I1) — status + cited sources per claim, never a truth verdict. */
export function buildVerificationNote(report: TraceReport): string {
  const pct = Math.round(report.traceScore * 100);
  const lines: string[] = [
    "Source-Trace — verification note",
    `Trace score: ${pct}% (share of claims with a visible source)`,
  ];
  if (report.flags.length > 0) {
    lines.push(`Flags: ${report.flags.map((f) => FLAG_LABEL[f]).join("; ")}`);
  }
  lines.push("");
  report.claims.forEach((c, i) => {
    lines.push(`${i + 1}. [${STATUS_LABEL[c.status]}] ${c.text}`);
    const srcs = c.matchedSourceIndexes
      .map((idx) => report.sources[idx])
      .filter((s): s is Source => Boolean(s))
      .map((s) => {
        const hint = publisherHint(s.domain);
        return hint ? `${sourceLabel(s)} (${hint.long})` : sourceLabel(s);
      });
    if (srcs.length > 0) lines.push(`   sources: ${srcs.join(", ")}`);
  });
  lines.push("");
  lines.push("Describes visible sourcing, not truth. Generated by Source-Trace.");
  return lines.join("\n");
}

/** Short, human label for a cited source shown next to a claim. */
export function sourceLabel(s: Source): string {
  if (s.domain) return s.domain;
  try {
    return new URL(s.url).hostname.replace(/^www\./, "");
  } catch {
    return s.url;
  }
}

/** A trace action: reverse-search the claim phrase for a primary source. */
export function reverseSearchUrl(claimText: string): string {
  const q = claimText.length > 120 ? claimText.slice(0, 120) : claimText;
  return `https://www.google.com/search?q=${encodeURIComponent(`"${q}"`)}`;
}

/** "Find a second source" — same phrase, encourage a different origin. */
export function secondSourceUrl(claimText: string): string {
  const q = claimText.length > 120 ? claimText.slice(0, 120) : claimText;
  return `https://www.google.com/search?q=${encodeURIComponent(`${q} -site:wikipedia.org`)}`;
}
